import Head from 'next/head'
import Avatar from '../components/Avatar'
import { ViewGridIcon, MicrophoneIcon} from '@heroicons/react/solid';
import {SearchIcon} from '@heroicons/react/outline'
import Image from 'next/image';
import Footer from '../components/Footer';
import { useRef } from 'react';
import { useRouter } from 'next/router';

export default function Home() {

  const router = useRouter();
  const searchInputRef = useRef(null);

  const search = (e) => {
    e.preventDefault();
    const term = searchInputRef.current.value;

    if (!term) {
      return;
    }

    router.push(`/search?term=${term}`);
  }

  return (
    <div className='flex flex-col items-center justify-center h-screen'>
      <Head>
        <title>google 2.0</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>

      <header className='flex justify-between items-center p-5 text-sm text-gray-700 w-full'>
        <div className='flex space-x-4 items-center'>
          <p className='link'>About</p>
          <p className='link'>Store</p>
        </div>
        <div className='flex space-x-4 items-center'>
          <p className='link'>Gmail</p>
          <p className='link'>Images</p>
          <ViewGridIcon className='h-10 w-10 p-2 rounded-full hover:bg-gray-100 cursor-pointer'/>
          <Avatar url="/user-profile.png"/>
        </div>
      </header>

      <form className='flex flex-col items-center mt-26 flex-grow w-4/5'>
        <Image src="/google-logo.png" alt="google-logo" height={100} width={300} />
        <div className='w-full flex mt-5 hover:shadow-lg focus-within:shadow-lg max-w-md rounded-full border border-gray-200 px-5 py-3 items-center sm:max-w-xl lg:max-w-2xl'>
          <SearchIcon className='h-5 mr-3 text-gray-500 cursor-pointer' />
          <input ref={searchInputRef} type="text" className='focus:outline-none flex-grow' />
          <MicrophoneIcon className='h-5 cursor-pointer'/>
        </div>
        <div className='flex flex-col w-1/2 space-y-2 justify-center mt-8 sm:space-y-0 sm:flex-row sm:space-x-4'>
          <button type='submit' className='btn' onClick={search}>Google Search</button>
          <button type='submit' className='btn' onClick={search}>I'm Feeling Lucky</button>
        </div>
      </form>

      <Footer/>
      
    </div>
  )
}
